name: urlb
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - absl-py=0.13.0
  - torchaudio
  - numpy=1.24.4
  - torchvision
  - jupyterlab=3.0.14
  - pytorch
  - cudatoolkit=11.1
  - scikit-image=0.18.1
  - protobuf=3.20.3
  - pip:
    - termcolor==1.1.0
    - dm-control==1.0.20
    - tb-nightly==2.14.0a20230808
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - pandas==1.3.0
    - ipdb==0.13.9
    - yapf==0.31.0
    - sklearn==0.0
    - matplotlib==3.4.2
    - opencv-python==4.5.3.56
    - wandb==0.11.1
    - moviepy==1.0.3
