name: urlb
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - absl-py=0.13.0
  - torchaudio
  - numpy=1.24.4
  - torchvision
  - jupyterlab=3.0.14
  - pytorch
  - cudatoolkit=11.1
  - scikit-image=0.18.1
  - protobuf=3.20.3
  - pip:
    - antlr4-python3-runtime==4.8
    - cachetools==5.5.2
    - configparser==7.1.0
    - decorator==4.4.2
    - dm-control==1.0.20
    - dm-env==1.6
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - etils==1.3.0
    - gitdb==4.0.12
    - gitpython==3.1.45
    - glfw==2.9.0
    - google-auth-oauthlib==1.0.0
    - google-auth==2.40.3
    - graphql-core==3.2.6
    - grpcio==1.70.0
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - imageio-ffmpeg==0.4.4
    - imageio==2.9.0
    - ipdb==0.13.9
    - joblib==1.4.2
    - labmaze==1.0.6
    - lxml==6.0.0
    - markdown==3.7
    - matplotlib==3.4.2
    - moviepy==1.0.3
    - mujoco==3.1.6
    - oauthlib==3.3.1
    - omegaconf==2.1.2
    - opencv-python==4.5.3.56
    - pandas==1.3.0
    - pathtools==0.1.2
    - proglog==0.1.12
    - promise==2.3
    - protobuf==3.20.3
    - pyasn1-modules==0.4.2
    - pyasn1==0.6.1
    - pyopengl==3.1.9
    - pyparsing==3.1.4
    - requests-oauthlib==2.0.0
    - rsa==4.9.1
    - scikit-learn==1.3.2
    - sentry-sdk==2.35.0
    - shortuuid==1.0.13
    - sklearn==0.0
    - smmap==5.0.2
    - submitit==1.5.3
    - tb-nightly==2.14.0a20230808
    - tensorboard-data-server==0.7.2
    - termcolor==1.1.0
    - threadpoolctl==3.5.0
    - toml==0.10.2
    - tqdm==4.67.1
    - wandb==0.11.1
    - werkzeug==3.0.6
    - yapf==0.31.0
